---
- name: Ensure sensu container exists
  docker_container:
    command: sensu-backend start --state-dir /var/lib/sensu/sensu-backend --log-level {{ sensu_backend_log_level }}
    env: "{{ sensu_backend_docker_env }}"
    image: "{{ sensu_backend_docker_image }}:{{ sensu_backend_docker_tag }}"
    name: sensu-backend
    ports:
      - "{{ sensu_backend_webui_port }}:3000"
      - "{{ sensu_backend_api_port }}:8080"
      - "{{ sensu_backend_websocket_port }}:8081"
    restart_policy: "{{ sensu_backend_restart_policy }}"
    volumes:
      - "{{ sensu_backend_host_data_path }}:/var/lib/sensu"
    state: started
