---
- name: Ensure sensu container exists
  docker_container:
    command: sensu-backend start --state-dir /var/lib/sensu/sensu-backend --log-level {{ sensu_backend_log_level }}
    env: "{{ sensu_backend_docker_env }}"
    image: "{{ sensu_backend_docker_image }}:{{ sensu_backend_docker_tag }}"
    name: sensu-backend
    network_mode: "{{ sensu_backend_network_mode }}"
    ports: "{{ sensu_backend_ports }}"
    restart_policy: "{{ sensu_backend_restart_policy }}"
    volumes:
      - "{{ sensu_backend_host_data_path }}:/var/lib/sensu"
    state: "{{ sensu_backend_container_state }}"
