---
dependency:
  name: galaxy
  enabled: False

driver:
  name: docker

lint: |
    yamllint .
    ansible-lint
    flake8

provisioner:
  name: ansible
  playbooks:
    cleanup: ../shared/cleanup.yml
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml

verifier:
  name: testinfra
  directory: ../shared/tests/
